import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  Container,
  Paper,
  Typography,
  Box,
  TextField,
  Button,
  Grid,
  Alert,
  CircularProgress,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
} from '@mui/material';
import {
  ArrowBack as BackIcon,
  Save as SaveIcon,
} from '@mui/icons-material';
import { AdminLayout } from '../../components/layouts/AdminLayout';
import { useApiQuery } from '../../hooks/useQuery';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import apiClient from '../../utils/apiClient';
import { API_ENDPOINTS } from '../../config/api';
import { Loading } from '../../components/common/Loading';
import { useToast } from '../../components/common/Toast';

export const CompanyFormPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { showToast } = useToast();
  const queryClient = useQueryClient();
  const isEdit = !!id;

  const [formData, setFormData] = useState({
    name: '',
    slug: '',
    status: 'active',
    description: '',
  });
  const [errors, setErrors] = useState({});
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(false);

  const { data, isLoading } = useApiQuery(
    ['admin', 'company', id],
    API_ENDPOINTS.ADMIN.PLATFORM.COMPANY_DETAIL(id),
    { enabled: isEdit }
  );

  useEffect(() => {
    if (isEdit && data?.data) {
      const company = data.data;
      setFormData({
        name: company.name || '',
        slug: company.slug || '',
        status: company.status || 'active',
        description: company.description || '',
      });
    }
  }, [isEdit, data]);

  // Auto-generate slug from name
  useEffect(() => {
    if (!isEdit && formData.name && !slugAutoGenerated) {
      const slug = formData.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '');
      setFormData((prev) => ({ ...prev, slug }));
      setSlugAutoGenerated(true);
    }
  }, [formData.name, isEdit, slugAutoGenerated]);

  const createMutation = useMutation({
    mutationFn: async (data) => {
      const response = await apiClient.post(
        API_ENDPOINTS.ADMIN.PLATFORM.COMPANIES,
        data
      );
      return response.data;
    },
    onSuccess: () => {
      showToast('Company created successfully', 'success');
      queryClient.invalidateQueries({ queryKey: ['admin', 'companies'] });
      navigate('/admin/companies');
    },
    onError: (error) => {
      const errorData = error.response?.data;
      if (errorData?.errors) {
        setErrors(errorData.errors);
      } else {
        showToast(errorData?.message || 'Failed to create company', 'error');
      }
    },
  });

  const updateMutation = useMutation({
    mutationFn: async ({ id, data }) => {
      const response = await apiClient.patch(
        API_ENDPOINTS.ADMIN.PLATFORM.COMPANY_DETAIL(id),
        data
      );
      return response.data;
    },
    onSuccess: () => {
      showToast('Company updated successfully', 'success');
      queryClient.invalidateQueries({ queryKey: ['admin', 'companies'] });
      queryClient.invalidateQueries({ queryKey: ['admin', 'company', id] });
      navigate(`/admin/companies/${id}`);
    },
    onError: (error) => {
      const errorData = error.response?.data;
      if (errorData?.errors) {
        setErrors(errorData.errors);
      } else {
        showToast(errorData?.message || 'Failed to update company', 'error');
      }
    },
  });

  const handleChange = (field) => (e) => {
    const value = e.target.value;
    setFormData((prev) => ({ ...prev, [field]: value }));
    if (errors[field]) {
      setErrors((prev) => ({ ...prev, [field]: null }));
    }
    if (field === 'name' && !isEdit) {
      setSlugAutoGenerated(false);
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setErrors({});

    // Validation
    const newErrors = {};
    if (!formData.name.trim()) {
      newErrors.name = 'Company name is required';
    }
    if (!formData.slug.trim()) {
      newErrors.slug = 'Slug is required';
    } else if (!/^[a-z0-9-]+$/.test(formData.slug)) {
      newErrors.slug = 'Slug can only contain lowercase letters, numbers, and hyphens';
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    if (isEdit) {
      updateMutation.mutate({ id, data: formData });
    } else {
      createMutation.mutate(formData);
    }
  };

  if (isEdit && isLoading) {
    return (
      <AdminLayout>
        <Loading />
      </AdminLayout>
    );
  }

  const isLoadingMutation = createMutation.isLoading || updateMutation.isLoading;

  return (
    <AdminLayout>
      <Container maxWidth="md">
        <Box display="flex" alignItems="center" mb={3}>
          <Button
            startIcon={<BackIcon />}
            onClick={() => navigate(isEdit ? `/admin/companies/${id}` : '/admin/companies')}
            sx={{ mr: 2 }}
          >
            Back
          </Button>
          <Typography variant="h4">
            {isEdit ? 'Edit Company' : 'Add Company'}
          </Typography>
        </Box>

        <Paper sx={{ p: 3 }}>
          <form onSubmit={handleSubmit}>
            <Grid container spacing={3}>
              <Grid item xs={12}>
                <TextField
                  fullWidth
                  label="Company Name"
                  value={formData.name}
                  onChange={handleChange('name')}
                  required
                  error={!!errors.name}
                  helperText={errors.name}
                  disabled={isLoadingMutation}
                />
              </Grid>

              <Grid item xs={12}>
                <TextField
                  fullWidth
                  label="Slug"
                  value={formData.slug}
                  onChange={handleChange('slug')}
                  required
                  error={!!errors.slug}
                  helperText={errors.slug || 'URL-friendly identifier (lowercase, hyphens only)'}
                  disabled={isLoadingMutation}
                  InputProps={{
                    readOnly: isEdit, // Prevent slug changes on edit
                  }}
                />
              </Grid>

              <Grid item xs={12}>
                <TextField
                  fullWidth
                  select
                  label="Status"
                  value={formData.status}
                  onChange={handleChange('status')}
                  SelectProps={{
                    native: true,
                  }}
                  disabled={isLoadingMutation}
                >
                  <option value="active">Active</option>
                  <option value="suspended">Suspended</option>
                  <option value="inactive">Inactive</option>
                </TextField>
              </Grid>

              <Grid item xs={12}>
                <TextField
                  fullWidth
                  label="Description"
                  value={formData.description}
                  onChange={handleChange('description')}
                  multiline
                  rows={4}
                  disabled={isLoadingMutation}
                />
              </Grid>

              {Object.keys(errors).length > 0 && (
                <Grid item xs={12}>
                  <Alert severity="error">
                    Please fix the errors above
                  </Alert>
                </Grid>
              )}

              <Grid item xs={12}>
                <Box display="flex" justifyContent="flex-end" gap={2}>
                  <Button
                    variant="outlined"
                    onClick={() => navigate(isEdit ? `/admin/companies/${id}` : '/admin/companies')}
                    disabled={isLoadingMutation}
                  >
                    Cancel
                  </Button>
                  <Button
                    type="submit"
                    variant="contained"
                    startIcon={isLoadingMutation ? <CircularProgress size={20} /> : <SaveIcon />}
                    disabled={isLoadingMutation}
                  >
                    {isLoadingMutation ? 'Saving...' : isEdit ? 'Update Company' : 'Create Company'}
                  </Button>
                </Box>
              </Grid>
            </Grid>
          </form>
        </Paper>
      </Container>
    </AdminLayout>
  );
};

